config/routes.rb
Rails.application.routes.draw do
  resources :offers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/offer.rb
class Offer < ApplicationRecord
    has_one_attached :foto 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[ show edit update destroy ]

  # GET /offers or /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1 or /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers or /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to offer_url(@offer), notice: "Offer was successfully created." }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1 or /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to offer_url(@offer), notice: "Offer was successfully updated." }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1 or /offers/1.json
  def destroy
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to offers_url, notice: "Offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def offer_params
      params.require(:offer).permit(:rif, :titolo, :descrizione, :luogo, :foto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/home/_carousel.html.erb
<div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://images.unsplash.com/photo-1597058557804-95ac4ee36e66?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://images.unsplash.com/photo-1621905251918-48416bd8575a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1469&q=80" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/home/index.html.erb
<div class="container">
<%= render 'carousel' %>
    <h1>Home page</h1>
    <p>Qui ci sarà la presentazione del progetto JOB</p>
    <p>Più sotto le card con alcune offerte di lavoro in evidenza</p>
    
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="offers">offerte</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="it">
<html>
  <head>
    <meta charset="utf-8">
    <title>Job</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    


    <%= yield %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= form_with(model: offer) do |form| %>
  <% if offer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
        <% offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :rif, class: 'from-label' %>
    <%= form.number_field :rif, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :titolo, class: 'from-label' %>
    <%= form.text_field :titolo, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :descrizione, class: 'from-label' %>
    <%= form.text_area :descrizione, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :luogo, class: 'from-label' %>
    <%= form.text_field :luogo, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :foto, class: 'from-label' %>
    <%= form.file_field :foto, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.submit 'Salva', class: 'btn btn-primary w-100' %>
  </div>
<% end %>

app/views/offers/_offer.html.erb
<div id="<%= dom_id offer %>">
 <% if offer.foto.attached? %>
  <%= image_tag url_for(offer.foto), class: 'w-100' %>
 <% end %> 
  <p>
    <strong>Rif:</strong>
    <%= offer.rif %>
  </p>

  <p>
    <strong>Titolo:</strong>
    <%= offer.titolo %>
  </p>

  <p>
    <strong>Descrizione:</strong>
    <%= offer.descrizione %>
  </p>

  <p>
    <strong>Luogo:</strong>
    <%= offer.luogo %>
  </p>

</div>

app/views/offers/edit.html.erb
<div class="container">
  <h1>Modifica offerta di lavoro</h1>

  <%= render "form", offer: @offer %>

  <br>

  <div>
    <%= link_to "Visualizza l'offerta", @offer , class:'btn btn-success w-100'%> 
    <h1>  </h1>
    <%= link_to "Torna alle offerte", offers_path, class:'btn btn-secondary w-100' %>
  </div>
</div>

app/views/offers/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  
  <h1>Offerte</h1>

  <%= link_to "Nuova offerta", new_offer_path, class: 'btn btn-warning w-100' %>

  <div id="offers" class="row">
    <% @offers.each do |offer| %>
      <div class="col-4">
        <%= render offer %>
        <p>
          <%= link_to "Dettagli", offer, class: 'btn btn-primary w-100' %>
        </p>
      </div>
    <% end %>
  </div>

  
</div>

app/views/offers/new.html.erb
<div class="container">
  <h1>Nuova offerta di lavoro</h1>

  <%= render "form", offer: @offer %>

  <br>

  <div>
    <%= link_to "Torna alle offerte", offers_path %>
  </div>
</div>

app/views/offers/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @offer %>

  <div>
    <%= link_to "Modifica", edit_offer_path(@offer), class:'btn btn-warning w-100' %> 
     
    <%= button_to "Ellimina", @offer, method: :delete, class:'btn btn-danger w-100' %> 
    <%= link_to "Torna alle offerte", offers_path, class:'btn btn-secondary w-100'%>  

    
  </div>
</div>